import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import * as motion from "motion/react-client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <motion.body
        initial={{
          opacity: 0,
        }}
        animate={{
          opacity: 1,
        }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid place-content-center h-full bg-gray-950`}
      >
        {children}
      </motion.body>
    </html>
  );
}
