import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import * as motion from "motion/react-client";
import PetSelect from "@/components/PetSelect";
import PetSelectOptions from "@/components/PetSelect/PetSelectOptions";
import { slideUpAnimation } from "@/animations";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const transparentToOpaqueAnimation = {
  initial: {
    opacity: 0,
  },
  animate: {
    opacity: 1,
  },
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <motion.body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-gray-950`}
      >
        <motion.div {...transparentToOpaqueAnimation}>
          <motion.section
            {...slideUpAnimation}
            className="flex flex-col justify-center items-center"
          >
            <TitleTopSpacer />
            <h1 className="text-fluid-h1 text-center">Pet Enquiry</h1>
            <TitleBottomSpacer />
            {children}
          </motion.section>
        </motion.div>
      </motion.body>
    </html>
  );
}

function TitleTopSpacer() {
  return (
    <div
      style={{
        height: "clamp(2.5rem, 10vw, 5rem)",
      }}
    ></div>
  );
}

function TitleBottomSpacer() {
  return (
    <div
      style={{
        height: "24px",
      }}
    ></div>
  );
}
